In [1]:
# !python -m pip install -U python-woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-woc in /home/econstan/.local/lib/python3.9/site-packages (0.4.1)
Requirement already satisfied: pandas in /home/econstan/.local/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: matplotlib in /home/econstan/.local/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /home/econstan/.local/lib/python3.9/site-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /home/econstan/.local/lib/python3.9/site-packages (from python-woc) (0.28.1)
Requirement already satisfied: python-lzf<0.3.0,>=0.2.4 in /home/econstan/.local/lib/python3.9/site-packages (from python-woc) (0.2.6)
Requirement already satisfied: rapidgzip<0.15.0,>=0.14.3 in /home/econstan/.local/lib/python3.9/site-packages (from python-woc) (0.14.5)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /home/econstan/.local/lib/python3.9/site-packages (from python-woc) (4.70.1)
Requirement already satisfied: anyio in /home/econstan/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.12.1)
Requirement already satisfied: certifi in /home/econstan/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /home/econstan/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /usr/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2.10)
Requirement already satisfied: h11>=0.16 in /home/econstan/.local/lib/python3.9/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: numpy>=1.22.4 in /usr/lib64/python3.9/site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.9/site-packages (from pandas) (2021.1)
Requirement already satisfied: tzdata>=2022.7 in /home/econstan/.local/lib/python3.9/site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/econstan/.local/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.9/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/econstan/.local/lib/python3.9/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/lib64/python3.9/site-packages (from matplotlib) (1.4.1)
Requirement already satisfied: packaging>=20.0 in /home/econstan/.local/lib/python3.9/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/lib64/python3.9/site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3.9/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/econstan/.local/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (1.3.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.14.1)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [2]:
from woc.remote import WocMapsRemote 
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
# projects = ['mmorise/World']
projects = [
    "aidenlab/straw",
    "corybrunson/ggalluvial",
    "snowleopard/alga",
    "maximecb/gym-minigrid",
    "seung-lab/cloud-volume",
    "STVIR/pysot",
    "google-research/torchsde",
    "tidymodels/rsample",
    "coin-or/Ipopt",
    "OHDSI/PatientLevelPrediction",
]
list_df_commits = []
index = 0
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  # print(f"Retrieving: {prj}", flush=True)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits, ignore_index=True)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(10)

                                       sha1         project
0  014d06ce8337aab2b4d7e9da90d2d0d22537d118  aidenlab_straw
1  02ef30c2693b1cba6fd1e5d2d694803aeed0403d  aidenlab_straw
2  0397a5027626eab94a326650cb7bf8bf73e6084c  aidenlab_straw
3  03cf1d6674f4d3eeed208f55bd5e31f74b381151  aidenlab_straw
4  03fbfdc1d863e8aed6ce70bee27c54daab2d388b  aidenlab_straw
5  043329007b29d5b1cd79da01ba6f72a27606bd7d  aidenlab_straw
6  043684bef67e20f1e3543063be76830e4c299c78  aidenlab_straw
7  0542e0fdbac861f172b286a3ddd98248fb4b830f  aidenlab_straw
8  055d71f3203cd22026296d4e0a99506b356a4c78  aidenlab_straw
9  05f413f4207fd01abed54155563eb43d3c582bdb  aidenlab_straw

In [3]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  0%|          | 0/2274 [00:00<?, ?it/s]

  0%|          | 2/2274 [00:02<38:29,  1.02s/it]

Got Errors {'0686ed71f060208739b1da33c809ec7f73e48ff5': 'Key 0686ed71f060208739b1da33c809ec7f73e48ff5 not found in /da5_fast/All.sha1c/commit_6.tch'}

  1%|          | 12/2274 [00:12<38:18,  1.02s/it]

Got Errors {'4247b698dfcb8dde46198761994c3a94f00f2a06': 'Key 4247b698dfcb8dde46198761994c3a94f00f2a06 not found in /da5_fast/All.sha1c/commit_66.tch'}

  6%|▋         | 147/2274 [02:30<36:31,  1.03s/it]

Got Errors {'157092f935ba75d5d9dcd2831e9bb6e7cbe3a801': 'Key 157092f935ba75d5d9dcd2831e9bb6e7cbe3a801 not found in /da5_fast/All.sha1c/commit_21.tch'}

  7%|▋         | 153/2274 [02:37<36:28,  1.03s/it]

Got Errors {'1c8e2cd7a8d31953d1a8f40e367869e7ba720394': 'Key 1c8e2cd7a8d31953d1a8f40e367869e7ba720394 not found in /da5_fast/All.sha1c/commit_28.tch'}

  8%|▊         | 186/2274 [03:11<35:53,  1.03s/it]

Got Errors {'44deb3e375545169ce254301bfe5ab3b3fe287e5': 'Key 44deb3e375545169ce254301bfe5ab3b3fe287e5 not found in /da5_fast/All.sha1c/commit_68.tch'}

  9%|▉         | 201/2274 [03:26<35:40,  1.03s/it]

Got Errors {'5ab6638a56c2934c0c7c3dff09db9757c550b34f': 'Key 5ab6638a56c2934c0c7c3dff09db9757c550b34f not found in /da5_fast/All.sha1c/commit_90.tch'}

  9%|▉         | 205/2274 [03:30<35:36,  1.03s/it]

Got Errors {'5ee595abb559240ef9b0c0b9f032d24e554a9fe3': 'Key 5ee595abb559240ef9b0c0b9f032d24e554a9fe3 not found in /da5_fast/All.sha1c/commit_94.tch'}

  9%|▉         | 211/2274 [03:37<35:31,  1.03s/it]

Got Errors {'67ce4c502c4f7416eb42be7019071bc356c55362': 'Key 67ce4c502c4f7416eb42be7019071bc356c55362 not found in /da5_fast/All.sha1c/commit_103.tch'}

 10%|▉         | 221/2274 [03:47<35:15,  1.03s/it]

Got Errors {'742d8c2a507c13b941e671b7a55d991b2bea3c59': 'Key 742d8c2a507c13b941e671b7a55d991b2bea3c59 not found in /da5_fast/All.sha1c/commit_116.tch'}

 10%|█         | 232/2274 [03:58<35:08,  1.03s/it]

Got Errors {'83819bef999db96048f1b43eafd279fb7d1aa286': 'Key 83819bef999db96048f1b43eafd279fb7d1aa286 not found in /da5_fast/All.sha1c/commit_3.tch'}

 10%|█         | 235/2274 [04:01<35:00,  1.03s/it]

Got Errors {'86715f3d6d96f8577287d0cb300f6f3908fc05dd': 'Key 86715f3d6d96f8577287d0cb300f6f3908fc05dd not found in /da5_fast/All.sha1c/commit_6.tch'}

 11%|█         | 239/2274 [04:05<34:56,  1.03s/it]

Got Errors {'89f1980a7171c366f18cdf296d243ddf1eb8087e': 'Key 89f1980a7171c366f18cdf296d243ddf1eb8087e not found in /da5_fast/All.sha1c/commit_9.tch'}

 12%|█▏        | 268/2274 [04:35<34:28,  1.03s/it]

Got Errors {'ab521c2f954c80edcb605503ce4058b4f018dcc3': 'Key ab521c2f954c80edcb605503ce4058b4f018dcc3 not found in /da5_fast/All.sha1c/commit_43.tch'}

 12%|█▏        | 273/2274 [04:40<34:17,  1.03s/it]

Got Errors {'b108104c48bd91349321345650740143d1d9cd9b': 'Key b108104c48bd91349321345650740143d1d9cd9b not found in /da5_fast/All.sha1c/commit_49.tch'}

 12%|█▏        | 278/2274 [04:46<34:11,  1.03s/it]

Got Errors {'b620ad50ab2e6d779bdd51737169461e3f5cbdec': 'Key b620ad50ab2e6d779bdd51737169461e3f5cbdec not found in /da5_fast/All.sha1c/commit_54.tch'}

 12%|█▏        | 279/2274 [04:47<34:10,  1.03s/it]

Got Errors {'b76a51f69db7635a66437ae835ef75da67272035': 'Key b76a51f69db7635a66437ae835ef75da67272035 not found in /da5_fast/All.sha1c/commit_55.tch'}

 12%|█▏        | 283/2274 [04:51<34:11,  1.03s/it]

Got Errors {'bc86d47afdcfcedc6da9b6ce60b1aa6a50f35281': 'Key bc86d47afdcfcedc6da9b6ce60b1aa6a50f35281 not found in /da5_fast/All.sha1c/commit_60.tch'}

 14%|█▎        | 309/2274 [05:17<33:40,  1.03s/it]

Got Errors {'df4a64d9da78ad74cff2444a47a38aea413dcdb8': 'Key df4a64d9da78ad74cff2444a47a38aea413dcdb8 not found in /da5_fast/All.sha1c/commit_95.tch'}

 14%|█▍        | 321/2274 [05:30<33:32,  1.03s/it]

Got Errors {'ee8fbbca9ad708a7f34c7fc1a1fcd2033958daec': 'Key ee8fbbca9ad708a7f34c7fc1a1fcd2033958daec not found in /da5_fast/All.sha1c/commit_110.tch'}

 14%|█▍        | 323/2274 [05:32<33:28,  1.03s/it]

Got Errors {'f15f748e3a6d5da1dfbb0513ec1fb5662448dce3': 'Key f15f748e3a6d5da1dfbb0513ec1fb5662448dce3 not found in /da5_fast/All.sha1c/commit_113.tch'}

 14%|█▍        | 328/2274 [05:37<33:26,  1.03s/it]

Got Errors {'f70f807bf7e10428406bdad172b4a4790ca83d8e': 'Key f70f807bf7e10428406bdad172b4a4790ca83d8e not found in /da5_fast/All.sha1c/commit_119.tch'}

 15%|█▍        | 330/2274 [05:39<33:24,  1.03s/it]

Got Errors {'fa620e04b1aec6bdca2ffc6e9961258d2bb616f7': 'Key fa620e04b1aec6bdca2ffc6e9961258d2bb616f7 not found in /da5_fast/All.sha1c/commit_122.tch'}

 24%|██▍       | 548/2274 [09:25<29:47,  1.04s/it]

Got Errors {'01f4397b2a30699fdeaf8aaa61b0d7d98e0c84b1': 'Key 01f4397b2a30699fdeaf8aaa61b0d7d98e0c84b1 not found in /da5_fast/All.sha1c/commit_1.tch'}

 24%|██▍       | 549/2274 [09:26<29:46,  1.04s/it]

Got Errors {'0302bb980e4fac889b6e93279f610c5bf58182b8': 'Key 0302bb980e4fac889b6e93279f610c5bf58182b8 not found in /da5_fast/All.sha1c/commit_3.tch', '036fe33a8ca90dd0b80e405720e0a427c0a3225a': 'Key 036fe33a8ca90dd0b80e405720e0a427c0a3225a not found in /da5_fast/All.sha1c/commit_3.tch', '0383f3a485c6f57698c7381a20cdf998c9676b2c': 'Key 0383f3a485c6f57698c7381a20cdf998c9676b2c not found in /da5_fast/All.sha1c/commit_3.tch'}

 24%|██▍       | 551/2274 [09:28<29:44,  1.04s/it]

Got Errors {'04ced2029319682654b1ee00bacfd584f7e56741': 'Key 04ced2029319682654b1ee00bacfd584f7e56741 not found in /da5_fast/All.sha1c/commit_4.tch', '059cd1db74e6cfa503305631b08a08a509831038': 'Key 059cd1db74e6cfa503305631b08a08a509831038 not found in /da5_fast/All.sha1c/commit_5.tch'}

 24%|██▍       | 555/2274 [09:32<29:37,  1.03s/it]

Got Errors {'08093b03a06eb92f43b66ce7e09cb4f2343c73c9': 'Key 08093b03a06eb92f43b66ce7e09cb4f2343c73c9 not found in /da5_fast/All.sha1c/commit_8.tch'}

 24%|██▍       | 556/2274 [09:33<29:35,  1.03s/it]

Got Errors {'095616247706dab8df67ee2a46962f3245f46ebf': 'Key 095616247706dab8df67ee2a46962f3245f46ebf not found in /da5_fast/All.sha1c/commit_9.tch', '095cb8e19030688af8416cc75637b4f8f2127ec1': 'Key 095cb8e19030688af8416cc75637b4f8f2127ec1 not found in /da5_fast/All.sha1c/commit_9.tch'}

 25%|██▍       | 558/2274 [09:35<29:33,  1.03s/it]

Got Errors {'0a8b0ba0e3d304655d989399000a79175a74af18': 'Key 0a8b0ba0e3d304655d989399000a79175a74af18 not found in /da5_fast/All.sha1c/commit_10.tch'}

 25%|██▍       | 559/2274 [09:36<29:32,  1.03s/it]

Got Errors {'0add84e054c410c001fc0f8ae54ac7a42051f091': 'Key 0add84e054c410c001fc0f8ae54ac7a42051f091 not found in /da5_fast/All.sha1c/commit_10.tch', '0ae0cd33e0622332d8d356b6342b87f22ee59270': 'Key 0ae0cd33e0622332d8d356b6342b87f22ee59270 not found in /da5_fast/All.sha1c/commit_10.tch', '0b670ded476199ae27d0f92cca120efb72791e62': 'Key 0b670ded476199ae27d0f92cca120efb72791e62 not found in /da5_fast/All.sha1c/commit_11.tch'}

 25%|██▍       | 562/2274 [09:39<29:32,  1.04s/it]

Got Errors {'0d48c13f908b84e6b7ea8d7cac5f4fcfb2e7688e': 'Key 0d48c13f908b84e6b7ea8d7cac5f4fcfb2e7688e not found in /da5_fast/All.sha1c/commit_13.tch'}

 25%|██▍       | 565/2274 [09:42<29:31,  1.04s/it]

Got Errors {'0f3d13dc4ff837af99db50c550e204b8ce0b80ec': 'Key 0f3d13dc4ff837af99db50c550e204b8ce0b80ec not found in /da5_fast/All.sha1c/commit_15.tch'}

 25%|██▍       | 568/2274 [09:45<29:23,  1.03s/it]

Got Errors {'11c61910cc509ceae2692a48b819725fe7e66e97': 'Key 11c61910cc509ceae2692a48b819725fe7e66e97 not found in /da5_fast/All.sha1c/commit_17.tch'}

 25%|██▌       | 569/2274 [09:46<29:26,  1.04s/it]

Got Errors {'12f6e11c69dde8f25380ee37de1ced35951b1b33': 'Key 12f6e11c69dde8f25380ee37de1ced35951b1b33 not found in /da5_fast/All.sha1c/commit_18.tch'}

 25%|██▌       | 570/2274 [09:47<29:24,  1.04s/it]

Got Errors {'13604f0c6d72db63cbd10ba1081fea22147bed3a': 'Key 13604f0c6d72db63cbd10ba1081fea22147bed3a not found in /da5_fast/All.sha1c/commit_19.tch'}

 25%|██▌       | 571/2274 [09:48<29:22,  1.04s/it]

Got Errors {'149d20ce7a18e3f019e267fc60ed282f0129bfb4': 'Key 149d20ce7a18e3f019e267fc60ed282f0129bfb4 not found in /da5_fast/All.sha1c/commit_20.tch'}

 25%|██▌       | 573/2274 [09:51<29:20,  1.03s/it]

Got Errors {'1533304443bbf7c917c608bbf777f2bb323993b4': 'Key 1533304443bbf7c917c608bbf777f2bb323993b4 not found in /da5_fast/All.sha1c/commit_21.tch'}

 25%|██▌       | 575/2274 [09:53<29:19,  1.04s/it]

Got Errors {'1735a7852c7549fdeb9b9a414746d77172d170ca': 'Key 1735a7852c7549fdeb9b9a414746d77172d170ca not found in /da5_fast/All.sha1c/commit_23.tch'}

 26%|██▌       | 582/2274 [10:00<29:13,  1.04s/it]

Got Errors {'1dca02d991498370a55109c574c6247cf2d53d49': 'Key 1dca02d991498370a55109c574c6247cf2d53d49 not found in /da5_fast/All.sha1c/commit_29.tch'}

 26%|██▌       | 584/2274 [10:02<29:10,  1.04s/it]

Got Errors {'1faf7c5fa374deaeecddf807e00d750ca6900eec': 'Key 1faf7c5fa374deaeecddf807e00d750ca6900eec not found in /da5_fast/All.sha1c/commit_31.tch'}

 26%|██▌       | 585/2274 [10:03<29:09,  1.04s/it]

Got Errors {'20b91bb574f21ccd12bf1966ba4a33618d9fcae1': 'Key 20b91bb574f21ccd12bf1966ba4a33618d9fcae1 not found in /da5_fast/All.sha1c/commit_32.tch'}

 26%|██▌       | 588/2274 [10:06<29:03,  1.03s/it]

Got Errors {'2387bdb433b15f9371d0453d7861f584ceaeb830': 'Key 2387bdb433b15f9371d0453d7861f584ceaeb830 not found in /da5_fast/All.sha1c/commit_35.tch'}

 26%|██▌       | 589/2274 [10:07<29:03,  1.03s/it]

Got Errors {'244aae79b55b898efdaecf9a84fc90b9ca06d742': 'Key 244aae79b55b898efdaecf9a84fc90b9ca06d742 not found in /da5_fast/All.sha1c/commit_36.tch'}

 26%|██▌       | 591/2274 [10:09<29:04,  1.04s/it]

Got Errors {'25cd65fb3c1b7f706ade4587f6f322a7164298b2': 'Key 25cd65fb3c1b7f706ade4587f6f322a7164298b2 not found in /da5_fast/All.sha1c/commit_37.tch'}

 26%|██▌       | 593/2274 [10:11<29:01,  1.04s/it]

Got Errors {'27be4f8544258c94b3fd474244a918e3f3839ca8': 'Key 27be4f8544258c94b3fd474244a918e3f3839ca8 not found in /da5_fast/All.sha1c/commit_39.tch'}

 26%|██▌       | 595/2274 [10:13<29:01,  1.04s/it]

Got Errors {'2913b4f42cb8dae1078cd45ba267d7e270c0a040': 'Key 2913b4f42cb8dae1078cd45ba267d7e270c0a040 not found in /da5_fast/All.sha1c/commit_41.tch'}

 26%|██▌       | 596/2274 [10:14<28:59,  1.04s/it]

Got Errors {'297fe12b78bcb271b32824b91dea5f6db3eb58ba': 'Key 297fe12b78bcb271b32824b91dea5f6db3eb58ba not found in /da5_fast/All.sha1c/commit_41.tch'}

 26%|██▋       | 601/2274 [10:20<28:51,  1.03s/it]

Got Errors {'2cda2bcc3ff8c9dd34bb57bc5479123c89b700be': 'Key 2cda2bcc3ff8c9dd34bb57bc5479123c89b700be not found in /da5_fast/All.sha1c/commit_44.tch'}

 26%|██▋       | 602/2274 [10:21<28:51,  1.04s/it]

Got Errors {'2dffa95c5fbf85b9ea9e4ffdcdda571a4365198b': 'Key 2dffa95c5fbf85b9ea9e4ffdcdda571a4365198b not found in /da5_fast/All.sha1c/commit_45.tch'}

 27%|██▋       | 603/2274 [10:22<28:50,  1.04s/it]

Got Errors {'2eb7cf2f44271255e6274d77126923fc61c9d934': 'Key 2eb7cf2f44271255e6274d77126923fc61c9d934 not found in /da5_fast/All.sha1c/commit_46.tch'}

 27%|██▋       | 612/2274 [10:31<28:42,  1.04s/it]

Got Errors {'363031568d6df6bead50623ef9086fb3243ef872': 'Key 363031568d6df6bead50623ef9086fb3243ef872 not found in /da5_fast/All.sha1c/commit_54.tch'}

 27%|██▋       | 614/2274 [10:33<28:37,  1.03s/it]

Got Errors {'37586613540f57d03f283ee6ddf6feb5ef83cebf': 'Key 37586613540f57d03f283ee6ddf6feb5ef83cebf not found in /da5_fast/All.sha1c/commit_55.tch'}

 27%|██▋       | 616/2274 [10:35<28:36,  1.04s/it]

Got Errors {'38aaa43d8fd2605d3cee1c079610fabdb142e0b4': 'Key 38aaa43d8fd2605d3cee1c079610fabdb142e0b4 not found in /da5_fast/All.sha1c/commit_56.tch'}

 27%|██▋       | 617/2274 [10:36<28:32,  1.03s/it]

Got Errors {'39acde5b50228f419d65321bd92f4ae3c8247aa3': 'Key 39acde5b50228f419d65321bd92f4ae3c8247aa3 not found in /da5_fast/All.sha1c/commit_57.tch'}

 27%|██▋       | 620/2274 [10:39<28:30,  1.03s/it]

Got Errors {'3bcdaab5db02bb3cb3813ac75c457add81e9b45f': 'Key 3bcdaab5db02bb3cb3813ac75c457add81e9b45f not found in /da5_fast/All.sha1c/commit_59.tch'}

 27%|██▋       | 623/2274 [10:42<28:26,  1.03s/it]

Got Errors {'3d420b9df3eb62bb2e6b84df486ce0e6cd730afc': 'Key 3d420b9df3eb62bb2e6b84df486ce0e6cd730afc not found in /da5_fast/All.sha1c/commit_61.tch', '3def247059bd8c8afd3ef628bdaa203f32c195e7': 'Key 3def247059bd8c8afd3ef628bdaa203f32c195e7 not found in /da5_fast/All.sha1c/commit_61.tch'}

 27%|██▋       | 624/2274 [10:43<28:22,  1.03s/it]

Got Errors {'3ea5a765a010677e94cf432bd16e016bda115f42': 'Key 3ea5a765a010677e94cf432bd16e016bda115f42 not found in /da5_fast/All.sha1c/commit_62.tch'}

 28%|██▊       | 626/2274 [10:45<28:22,  1.03s/it]

Got Errors {'3fc5e00f0fd678cfaee15dd50c38d6bfc2730449': 'Key 3fc5e00f0fd678cfaee15dd50c38d6bfc2730449 not found in /da5_fast/All.sha1c/commit_63.tch'}

 28%|██▊       | 627/2274 [10:46<28:20,  1.03s/it]

Got Errors {'40157422e2df405eb215582ee578056cd30ac29e': 'Key 40157422e2df405eb215582ee578056cd30ac29e not found in /da5_fast/All.sha1c/commit_64.tch', '403f3cf7ded9f7d78cf8d22b8429debbf76966fb': 'Key 403f3cf7ded9f7d78cf8d22b8429debbf76966fb not found in /da5_fast/All.sha1c/commit_64.tch'}

 28%|██▊       | 631/2274 [10:51<28:18,  1.03s/it]

Got Errors {'42bbf76f33897eaaf562d0b8460152ef03bcfb0e': 'Key 42bbf76f33897eaaf562d0b8460152ef03bcfb0e not found in /da5_fast/All.sha1c/commit_66.tch'}

 28%|██▊       | 639/2274 [10:59<28:11,  1.03s/it]

Got Errors {'490392d561edfce2fe04001e6e95383c6be8e9e2': 'Key 490392d561edfce2fe04001e6e95383c6be8e9e2 not found in /da5_fast/All.sha1c/commit_73.tch'}

 28%|██▊       | 642/2274 [11:02<28:08,  1.03s/it]

Got Errors {'4b92329a64cf8a1e8cad3af539066f66b5700795': 'Key 4b92329a64cf8a1e8cad3af539066f66b5700795 not found in /da5_fast/All.sha1c/commit_75.tch'}

 28%|██▊       | 646/2274 [11:06<28:05,  1.04s/it]

Got Errors {'4e6fee1ac77305739a0f1bce91dcce0f0cefa6d4': 'Key 4e6fee1ac77305739a0f1bce91dcce0f0cefa6d4 not found in /da5_fast/All.sha1c/commit_78.tch'}

 28%|██▊       | 647/2274 [11:07<28:02,  1.03s/it]

Got Errors {'4f17802b1c63e440a3aad7d4d13e3465e050db8f': 'Key 4f17802b1c63e440a3aad7d4d13e3465e050db8f not found in /da5_fast/All.sha1c/commit_79.tch'}

 28%|██▊       | 648/2274 [11:08<28:02,  1.03s/it]

Got Errors {'4fb95ec4ccde0853606f4d9681b15460181faeed': 'Key 4fb95ec4ccde0853606f4d9681b15460181faeed not found in /da5_fast/All.sha1c/commit_79.tch'}

 29%|██▊       | 652/2274 [11:12<27:58,  1.03s/it]

Got Errors {'528751e63bf8eca70bb54fe2f97c6877cbd76c4a': 'Key 528751e63bf8eca70bb54fe2f97c6877cbd76c4a not found in /da5_fast/All.sha1c/commit_82.tch'}

 29%|██▊       | 653/2274 [11:13<27:56,  1.03s/it]

Got Errors {'5362eb8807625df47a16c46e7cb6a89506eedd42': 'Key 5362eb8807625df47a16c46e7cb6a89506eedd42 not found in /da5_fast/All.sha1c/commit_83.tch'}

 29%|██▉       | 655/2274 [11:15<27:53,  1.03s/it]

Got Errors {'54bce7ce9de90e4c580048e8dfa76d118cc5e93b': 'Key 54bce7ce9de90e4c580048e8dfa76d118cc5e93b not found in /da5_fast/All.sha1c/commit_84.tch', '55147fc1ea80414a413a993d0bb5e8b0930a461b': 'Key 55147fc1ea80414a413a993d0bb5e8b0930a461b not found in /da5_fast/All.sha1c/commit_85.tch'}

 29%|██▉       | 665/2274 [11:26<27:44,  1.03s/it]

Got Errors {'5c31f2cc952d0c2284fc03aaf7ec1fc34f8b1d03': 'Key 5c31f2cc952d0c2284fc03aaf7ec1fc34f8b1d03 not found in /da5_fast/All.sha1c/commit_92.tch'}

 30%|██▉       | 671/2274 [11:32<27:37,  1.03s/it]

Got Errors {'5fd0e64d13f7c01cfbd8d95f65ee77b0ea3a19e4': 'Key 5fd0e64d13f7c01cfbd8d95f65ee77b0ea3a19e4 not found in /da5_fast/All.sha1c/commit_95.tch'}

 30%|██▉       | 672/2274 [11:33<27:36,  1.03s/it]

Got Errors {'60716ea0b7dfaf05cc1b9f2d5b9d88756917872f': 'Key 60716ea0b7dfaf05cc1b9f2d5b9d88756917872f not found in /da5_fast/All.sha1c/commit_96.tch', '60a77a91f7edb52effadae986ec19f27a09293b8': 'Key 60a77a91f7edb52effadae986ec19f27a09293b8 not found in /da5_fast/All.sha1c/commit_96.tch'}

 30%|██▉       | 673/2274 [11:34<27:37,  1.04s/it]

Got Errors {'6138a52eecc677ad536384c23607c67e8350a2c4': 'Key 6138a52eecc677ad536384c23607c67e8350a2c4 not found in /da5_fast/All.sha1c/commit_97.tch'}

 30%|██▉       | 678/2274 [11:39<27:34,  1.04s/it]

Got Errors {'642ab343da4c173ee28085736ffc408e7d454f47': 'Key 642ab343da4c173ee28085736ffc408e7d454f47 not found in /da5_fast/All.sha1c/commit_100.tch', '645d7d8a0666101ae68d315c971de4a53256618d': 'Key 645d7d8a0666101ae68d315c971de4a53256618d not found in /da5_fast/All.sha1c/commit_100.tch'}

 30%|██▉       | 679/2274 [11:40<27:30,  1.03s/it]

Got Errors {'65286d28893e9e0b187946054e95fd3f291cb176': 'Key 65286d28893e9e0b187946054e95fd3f291cb176 not found in /da5_fast/All.sha1c/commit_101.tch'}

 30%|██▉       | 680/2274 [11:41<27:29,  1.03s/it]

Got Errors {'6578a9615d0e4ad7f7965a5f28800c17da5d432c': 'Key 6578a9615d0e4ad7f7965a5f28800c17da5d432c not found in /da5_fast/All.sha1c/commit_101.tch', '65aece6c71df63549bc7ef64f8c7a1517a45619b': 'Key 65aece6c71df63549bc7ef64f8c7a1517a45619b not found in /da5_fast/All.sha1c/commit_101.tch'}

 30%|███       | 684/2274 [11:45<27:26,  1.04s/it]

Got Errors {'68e0188bdc048fed8bc668bbd019b895dce08ea0': 'Key 68e0188bdc048fed8bc668bbd019b895dce08ea0 not found in /da5_fast/All.sha1c/commit_104.tch'}

 30%|███       | 689/2274 [11:51<27:18,  1.03s/it]

Got Errors {'6bc7048fff8f45a17a456cfa735e7157cedc8135': 'Key 6bc7048fff8f45a17a456cfa735e7157cedc8135 not found in /da5_fast/All.sha1c/commit_107.tch'}

 30%|███       | 690/2274 [11:52<27:16,  1.03s/it]

Got Errors {'6bf55474d6537551191b553c12c8795e7fde4952': 'Key 6bf55474d6537551191b553c12c8795e7fde4952 not found in /da5_fast/All.sha1c/commit_107.tch'}

 30%|███       | 691/2274 [11:53<27:14,  1.03s/it]

Got Errors {'6ce2a789e03307a211b606117a5629d5e228d4a4': 'Key 6ce2a789e03307a211b606117a5629d5e228d4a4 not found in /da5_fast/All.sha1c/commit_108.tch'}

 30%|███       | 692/2274 [11:54<27:12,  1.03s/it]

Got Errors {'6d0b0ecd70cbbcf994cfcfa2eefff04c2a178aba': 'Key 6d0b0ecd70cbbcf994cfcfa2eefff04c2a178aba not found in /da5_fast/All.sha1c/commit_109.tch', '6d8b8a725211a91f10d5ebced49dc72e24b69b1a': 'Key 6d8b8a725211a91f10d5ebced49dc72e24b69b1a not found in /da5_fast/All.sha1c/commit_109.tch'}

 30%|███       | 693/2274 [11:55<27:11,  1.03s/it]

Got Errors {'6e13501954b8408bacd2095e9ac3ac0c4f1c0395': 'Key 6e13501954b8408bacd2095e9ac3ac0c4f1c0395 not found in /da5_fast/All.sha1c/commit_110.tch'}

 31%|███       | 695/2274 [11:57<27:12,  1.03s/it]

Got Errors {'701ca26ef486bf2f5983d601e248707edf5a05cf': 'Key 701ca26ef486bf2f5983d601e248707edf5a05cf not found in /da5_fast/All.sha1c/commit_112.tch', '70627586c019a9609821c70917a84c878f9e123c': 'Key 70627586c019a9609821c70917a84c878f9e123c not found in /da5_fast/All.sha1c/commit_112.tch'}

 31%|███       | 696/2274 [11:58<27:13,  1.03s/it]

Got Errors {'70b101fcb24db6bf82744644fe00fece24f49f3f': 'Key 70b101fcb24db6bf82744644fe00fece24f49f3f not found in /da5_fast/All.sha1c/commit_112.tch'}

 31%|███       | 698/2274 [12:00<27:14,  1.04s/it]

Got Errors {'717e0fdcb8be71a3890122a2fb2c562669e2befb': 'Key 717e0fdcb8be71a3890122a2fb2c562669e2befb not found in /da5_fast/All.sha1c/commit_113.tch'}

 31%|███       | 701/2274 [12:03<27:11,  1.04s/it]

Got Errors {'73df8e3c7d8f096e28253e1653ef428dd99c21a8': 'Key 73df8e3c7d8f096e28253e1653ef428dd99c21a8 not found in /da5_fast/All.sha1c/commit_115.tch'}

 31%|███       | 702/2274 [12:04<27:08,  1.04s/it]

Got Errors {'7492fc01786dd2077133ecf639437da24681f176': 'Key 7492fc01786dd2077133ecf639437da24681f176 not found in /da5_fast/All.sha1c/commit_116.tch'}

 31%|███       | 704/2274 [12:06<27:03,  1.03s/it]

Got Errors {'7636d6afe616016ac2055f9ff1ff6f62fdbd1088': 'Key 7636d6afe616016ac2055f9ff1ff6f62fdbd1088 not found in /da5_fast/All.sha1c/commit_118.tch', '763d4c476d6f9444e5139d2386b48b06be3820ad': 'Key 763d4c476d6f9444e5139d2386b48b06be3820ad not found in /da5_fast/All.sha1c/commit_118.tch'}

 31%|███       | 705/2274 [12:07<27:02,  1.03s/it]

Got Errors {'76882c41eb8e3e66465cd727afb89ccb85ebb221': 'Key 76882c41eb8e3e66465cd727afb89ccb85ebb221 not found in /da5_fast/All.sha1c/commit_118.tch', '76ad2cfe38abac93c8686d7103b784bed7c5e468': 'Key 76ad2cfe38abac93c8686d7103b784bed7c5e468 not found in /da5_fast/All.sha1c/commit_118.tch'}

 31%|███       | 706/2274 [12:08<27:01,  1.03s/it]

Got Errors {'77bd42f51e9ebe563ed4f20162dfef359c900394': 'Key 77bd42f51e9ebe563ed4f20162dfef359c900394 not found in /da5_fast/All.sha1c/commit_119.tch'}

 31%|███       | 709/2274 [12:11<27:03,  1.04s/it]

Got Errors {'793e4ac0c6f71741fcbc1ba9e74bf6aab0a74bd2': 'Key 793e4ac0c6f71741fcbc1ba9e74bf6aab0a74bd2 not found in /da5_fast/All.sha1c/commit_121.tch', '7956bdb87b675bd0c6d9619e88a9a05fdbfeab28': 'Key 7956bdb87b675bd0c6d9619e88a9a05fdbfeab28 not found in /da5_fast/All.sha1c/commit_121.tch', '795ccfceacbe7395f9c45f95701d7312a388d646': 'Key 795ccfceacbe7395f9c45f95701d7312a388d646 not found in /da5_fast/All.sha1c/commit_121.tch'}

 31%|███▏      | 715/2274 [12:17<26:53,  1.04s/it]

Got Errors {'7e0cdb8ff13fdb3a72f1569f1db78aa5c1e47eae': 'Key 7e0cdb8ff13fdb3a72f1569f1db78aa5c1e47eae not found in /da5_fast/All.sha1c/commit_126.tch'}

 31%|███▏      | 716/2274 [12:19<26:53,  1.04s/it]

Got Errors {'7e91a7e49d62d011428f4a8f4d25f08d1c31dfc1': 'Key 7e91a7e49d62d011428f4a8f4d25f08d1c31dfc1 not found in /da5_fast/All.sha1c/commit_126.tch', '7eae47d4ef28b85fbe3049c88b8208ab35bed292': 'Key 7eae47d4ef28b85fbe3049c88b8208ab35bed292 not found in /da5_fast/All.sha1c/commit_126.tch'}

 32%|███▏      | 717/2274 [12:20<26:53,  1.04s/it]

Got Errors {'8055bd38eeec7f50ae3ea0bdcd19102aab4677a6': 'Key 8055bd38eeec7f50ae3ea0bdcd19102aab4677a6 not found in /da5_fast/All.sha1c/commit_0.tch'}

 32%|███▏      | 718/2274 [12:21<26:51,  1.04s/it]

Got Errors {'805d0627db8b9a197830a10bf857a8145cb99fe0': 'Key 805d0627db8b9a197830a10bf857a8145cb99fe0 not found in /da5_fast/All.sha1c/commit_0.tch'}

 32%|███▏      | 722/2274 [12:25<26:43,  1.03s/it]

Got Errors {'82f6efd89771526bc1d4ad59f03f986bf689061c': 'Key 82f6efd89771526bc1d4ad59f03f986bf689061c not found in /da5_fast/All.sha1c/commit_2.tch'}

 32%|███▏      | 726/2274 [12:29<26:37,  1.03s/it]

Got Errors {'85f2a2546768f003169bc2b890b404505343359e': 'Key 85f2a2546768f003169bc2b890b404505343359e not found in /da5_fast/All.sha1c/commit_5.tch', '86278c441067f2ce18309ab1997c0eefc7b787f9': 'Key 86278c441067f2ce18309ab1997c0eefc7b787f9 not found in /da5_fast/All.sha1c/commit_6.tch'}

 32%|███▏      | 730/2274 [12:33<26:31,  1.03s/it]

Got Errors {'88af294f4fd6d101a527dd609e87b8707a0ecac0': 'Key 88af294f4fd6d101a527dd609e87b8707a0ecac0 not found in /da5_fast/All.sha1c/commit_8.tch', '88e4e84d1e491156fe904e638a865ee177a012c4': 'Key 88e4e84d1e491156fe904e638a865ee177a012c4 not found in /da5_fast/All.sha1c/commit_8.tch'}

 32%|███▏      | 732/2274 [12:35<26:31,  1.03s/it]

Got Errors {'89d0d42732c56899de7a55b29baa787821b0fff7': 'Key 89d0d42732c56899de7a55b29baa787821b0fff7 not found in /da5_fast/All.sha1c/commit_9.tch'}

 32%|███▏      | 734/2274 [12:37<26:29,  1.03s/it]

Got Errors {'8ab6063963e8887a76bba7f120432204ddb2b172': 'Key 8ab6063963e8887a76bba7f120432204ddb2b172 not found in /da5_fast/All.sha1c/commit_10.tch', '8ab71fab5a2c4969602b9de41de7975b2a000f76': 'Key 8ab71fab5a2c4969602b9de41de7975b2a000f76 not found in /da5_fast/All.sha1c/commit_10.tch'}

 32%|███▏      | 739/2274 [12:42<26:24,  1.03s/it]

Got Errors {'8e394d0815f9c6c9f2bb20f09061ae5ffc44f134': 'Key 8e394d0815f9c6c9f2bb20f09061ae5ffc44f134 not found in /da5_fast/All.sha1c/commit_14.tch', '8e411a6b7567c8dd02dba6dde05f3dbbed980138': 'Key 8e411a6b7567c8dd02dba6dde05f3dbbed980138 not found in /da5_fast/All.sha1c/commit_14.tch'}

 33%|███▎      | 740/2274 [12:43<26:23,  1.03s/it]

Got Errors {'8ea83e24879cb1486cf620a78e8df480e0515112': 'Key 8ea83e24879cb1486cf620a78e8df480e0515112 not found in /da5_fast/All.sha1c/commit_14.tch'}

 33%|███▎      | 748/2274 [12:52<26:14,  1.03s/it]

Got Errors {'93bf53899039bb7d027e5008b3cf71cc7dc7693e': 'Key 93bf53899039bb7d027e5008b3cf71cc7dc7693e not found in /da5_fast/All.sha1c/commit_19.tch'}

 33%|███▎      | 749/2274 [12:53<26:12,  1.03s/it]

Got Errors {'9513e29792bf623922ea9b5b67dfae66f08ba3a6': 'Key 9513e29792bf623922ea9b5b67dfae66f08ba3a6 not found in /da5_fast/All.sha1c/commit_21.tch'}

 33%|███▎      | 750/2274 [12:54<26:12,  1.03s/it]

Got Errors {'9529bb9692cc70f80cacb73c8f62dcc01a81a6af': 'Key 9529bb9692cc70f80cacb73c8f62dcc01a81a6af not found in /da5_fast/All.sha1c/commit_21.tch', '9531c65d8914b7d163f90b9d2333765963c85d94': 'Key 9531c65d8914b7d163f90b9d2333765963c85d94 not found in /da5_fast/All.sha1c/commit_21.tch'}

 33%|███▎      | 755/2274 [12:59<26:07,  1.03s/it]

Got Errors {'9965b248ccdcfb96d4575ffa867ea2ab9054aa03': 'Key 9965b248ccdcfb96d4575ffa867ea2ab9054aa03 not found in /da5_fast/All.sha1c/commit_25.tch'}

 33%|███▎      | 760/2274 [13:04<26:02,  1.03s/it]

Got Errors {'9c2601000042dc4588951bb113d4e4b9e41f92a8': 'Key 9c2601000042dc4588951bb113d4e4b9e41f92a8 not found in /da5_fast/All.sha1c/commit_28.tch'}

 34%|███▎      | 767/2274 [13:11<25:56,  1.03s/it]

Got Errors {'a096d55a71635227590e26abc2887c99bdc34b76': 'Key a096d55a71635227590e26abc2887c99bdc34b76 not found in /da5_fast/All.sha1c/commit_32.tch', 'a0cc3a23e15a7bc510d21515fbf1f63ebc4c1308': 'Key a0cc3a23e15a7bc510d21515fbf1f63ebc4c1308 not found in /da5_fast/All.sha1c/commit_32.tch'}

 34%|███▍      | 772/2274 [13:16<25:51,  1.03s/it]

Got Errors {'a3c870f60d660a0ea059be2be58e8c3b86af2ad0': 'Key a3c870f60d660a0ea059be2be58e8c3b86af2ad0 not found in /da5_fast/All.sha1c/commit_35.tch'}

 34%|███▍      | 774/2274 [13:18<25:46,  1.03s/it]

Got Errors {'a53dd775eab58353e59aac8ede7b50aa44fa763a': 'Key a53dd775eab58353e59aac8ede7b50aa44fa763a not found in /da5_fast/All.sha1c/commit_37.tch'}

 34%|███▍      | 775/2274 [13:19<25:44,  1.03s/it]

Got Errors {'a5a41188f2e73fbaefd0d209433f8aea05ccb159': 'Key a5a41188f2e73fbaefd0d209433f8aea05ccb159 not found in /da5_fast/All.sha1c/commit_37.tch'}

 34%|███▍      | 777/2274 [13:21<25:45,  1.03s/it]

Got Errors {'a760064b214179badf3834ab55d68f9bdebd04f2': 'Key a760064b214179badf3834ab55d68f9bdebd04f2 not found in /da5_fast/All.sha1c/commit_39.tch', 'a76d07ba1c703b137985bf8430064e93f60c95ed': 'Key a76d07ba1c703b137985bf8430064e93f60c95ed not found in /da5_fast/All.sha1c/commit_39.tch'}

 34%|███▍      | 779/2274 [13:24<25:42,  1.03s/it]

Got Errors {'a89d122a34cfc6a2f2d224ff7376ee9d8d0b7505': 'Key a89d122a34cfc6a2f2d224ff7376ee9d8d0b7505 not found in /da5_fast/All.sha1c/commit_40.tch'}

 34%|███▍      | 781/2274 [13:26<25:38,  1.03s/it]

Got Errors {'aa0e32fc2af98c86284f6580404389e55f64a9af': 'Key aa0e32fc2af98c86284f6580404389e55f64a9af not found in /da5_fast/All.sha1c/commit_42.tch'}

 34%|███▍      | 782/2274 [13:27<25:38,  1.03s/it]

Got Errors {'aa3c79070c3e0b0a126dc599482713b5592fed79': 'Key aa3c79070c3e0b0a126dc599482713b5592fed79 not found in /da5_fast/All.sha1c/commit_42.tch'}

 35%|███▍      | 791/2274 [13:36<25:27,  1.03s/it]

Got Errors {'af8981051fd845f8d5d26e7488e78100a8ada9cd': 'Key af8981051fd845f8d5d26e7488e78100a8ada9cd not found in /da5_fast/All.sha1c/commit_47.tch', 'afc30d34237f2772642bdcdcbcc0d6499151d7ae': 'Key afc30d34237f2772642bdcdcbcc0d6499151d7ae not found in /da5_fast/All.sha1c/commit_47.tch'}

 35%|███▍      | 792/2274 [13:37<25:28,  1.03s/it]

Got Errors {'b0065d7dbade94150ec5bd344165cde46b0a5975': 'Key b0065d7dbade94150ec5bd344165cde46b0a5975 not found in /da5_fast/All.sha1c/commit_48.tch'}

 35%|███▍      | 795/2274 [13:40<25:26,  1.03s/it]

Got Errors {'b36610c657466f11bc7fb47b35c0833871894464': 'Key b36610c657466f11bc7fb47b35c0833871894464 not found in /da5_fast/All.sha1c/commit_51.tch'}

 35%|███▌      | 796/2274 [13:41<25:27,  1.03s/it]

Got Errors {'b394803e2d683db3af649382427ef990d2c9b9b6': 'Key b394803e2d683db3af649382427ef990d2c9b9b6 not found in /da5_fast/All.sha1c/commit_51.tch'}

 35%|███▌      | 803/2274 [13:48<25:19,  1.03s/it]

Got Errors {'b8dd26773b6c1b7744c5561a6097c82d3ba46b34': 'Key b8dd26773b6c1b7744c5561a6097c82d3ba46b34 not found in /da5_fast/All.sha1c/commit_56.tch'}

 35%|███▌      | 807/2274 [13:52<25:12,  1.03s/it]

Got Errors {'ba9828a859a15369f080a30197f7ff782de83573': 'Key ba9828a859a15369f080a30197f7ff782de83573 not found in /da5_fast/All.sha1c/commit_58.tch', 'bb020f79d84304cb393c2a813f48be20442e0a60': 'Key bb020f79d84304cb393c2a813f48be20442e0a60 not found in /da5_fast/All.sha1c/commit_59.tch'}

 36%|███▌      | 808/2274 [13:53<25:13,  1.03s/it]

Got Errors {'bbaf312b8806f48508ef11d91da16a8d4c70c11e': 'Key bbaf312b8806f48508ef11d91da16a8d4c70c11e not found in /da5_fast/All.sha1c/commit_59.tch'}

 36%|███▌      | 810/2274 [13:56<25:10,  1.03s/it]

Got Errors {'bcd9528d5cad5b7e5dc781900dfa03f2a308027c': 'Key bcd9528d5cad5b7e5dc781900dfa03f2a308027c not found in /da5_fast/All.sha1c/commit_60.tch'}

 36%|███▌      | 811/2274 [13:57<25:09,  1.03s/it]

Got Errors {'bd30cac069c1aea4b94496035fc18dd32381ea59': 'Key bd30cac069c1aea4b94496035fc18dd32381ea59 not found in /da5_fast/All.sha1c/commit_61.tch'}

 36%|███▌      | 813/2274 [13:59<25:07,  1.03s/it]

Got Errors {'bedcc351b746910c8da0515de76ccd489116ca71': 'Key bedcc351b746910c8da0515de76ccd489116ca71 not found in /da5_fast/All.sha1c/commit_62.tch'}

 36%|███▌      | 815/2274 [14:01<25:06,  1.03s/it]

Got Errors {'bfb501508c40661340d0756638b88b30cd0488f5': 'Key bfb501508c40661340d0756638b88b30cd0488f5 not found in /da5_fast/All.sha1c/commit_63.tch'}

 36%|███▌      | 819/2274 [14:05<25:02,  1.03s/it]

Got Errors {'c234ffd9b0f0bf58e405003d2e04e2aeaed15be5': 'Key c234ffd9b0f0bf58e405003d2e04e2aeaed15be5 not found in /da5_fast/All.sha1c/commit_66.tch'}

 36%|███▌      | 820/2274 [14:06<25:00,  1.03s/it]

Got Errors {'c2b6093782bd01c0508cf765c755929009e48fa0': 'Key c2b6093782bd01c0508cf765c755929009e48fa0 not found in /da5_fast/All.sha1c/commit_66.tch'}

 36%|███▋      | 826/2274 [14:12<24:51,  1.03s/it]

Got Errors {'c67c32bf4892ea401be8501f847fc84324b90282': 'Key c67c32bf4892ea401be8501f847fc84324b90282 not found in /da5_fast/All.sha1c/commit_70.tch', 'c6929154d125c6647f7b0cd88164dd5c3bbf0fd5': 'Key c6929154d125c6647f7b0cd88164dd5c3bbf0fd5 not found in /da5_fast/All.sha1c/commit_70.tch'}

 36%|███▋      | 827/2274 [14:13<24:52,  1.03s/it]

Got Errors {'c72fb537b7fdb245b88e448139a8a934a5d1168b': 'Key c72fb537b7fdb245b88e448139a8a934a5d1168b not found in /da5_fast/All.sha1c/commit_71.tch'}

 36%|███▋      | 829/2274 [14:15<24:53,  1.03s/it]

Got Errors {'c819e0296418a25495bbff2c3fa818be39a0fd51': 'Key c819e0296418a25495bbff2c3fa818be39a0fd51 not found in /da5_fast/All.sha1c/commit_72.tch'}

 36%|███▋      | 830/2274 [14:16<24:49,  1.03s/it]

Got Errors {'c95d1b7483709327aee2785dce95c61b091272dd': 'Key c95d1b7483709327aee2785dce95c61b091272dd not found in /da5_fast/All.sha1c/commit_73.tch'}

 37%|███▋      | 831/2274 [14:17<24:47,  1.03s/it]

Got Errors {'c97b0e7260ae5780871d1f9e77e6ea8f72fe2430': 'Key c97b0e7260ae5780871d1f9e77e6ea8f72fe2430 not found in /da5_fast/All.sha1c/commit_73.tch', 'c98640f1ac324b177beaa26cdf967abbf96b35e4': 'Key c98640f1ac324b177beaa26cdf967abbf96b35e4 not found in /da5_fast/All.sha1c/commit_73.tch', 'c9bd0f195647fb42da4823ace43b40fc053eb19a': 'Key c9bd0f195647fb42da4823ace43b40fc053eb19a not found in /da5_fast/All.sha1c/commit_73.tch'}

 37%|███▋      | 832/2274 [14:18<24:48,  1.03s/it]

Got Errors {'c9f135bce10ab2fe590d240bf72acd66fbd9c779': 'Key c9f135bce10ab2fe590d240bf72acd66fbd9c779 not found in /da5_fast/All.sha1c/commit_73.tch'}

 37%|███▋      | 833/2274 [14:19<24:48,  1.03s/it]

Got Errors {'ca54f4df1b7f9b6679278754cde0db037a5fa4ff': 'Key ca54f4df1b7f9b6679278754cde0db037a5fa4ff not found in /da5_fast/All.sha1c/commit_74.tch'}

 37%|███▋      | 834/2274 [14:20<24:45,  1.03s/it]

Got Errors {'cae9865b8adb814283088e4d6af2ac4c8855d8ca': 'Key cae9865b8adb814283088e4d6af2ac4c8855d8ca not found in /da5_fast/All.sha1c/commit_74.tch'}

 37%|███▋      | 835/2274 [14:21<24:45,  1.03s/it]

Got Errors {'cb9becee9018115eb9b9340f3201219260b54646': 'Key cb9becee9018115eb9b9340f3201219260b54646 not found in /da5_fast/All.sha1c/commit_75.tch', 'cbbb65e5554373928c40dbb8052dabdc2a0f016b': 'Key cbbb65e5554373928c40dbb8052dabdc2a0f016b not found in /da5_fast/All.sha1c/commit_75.tch'}

 37%|███▋      | 836/2274 [14:22<24:45,  1.03s/it]

Got Errors {'cc1dbdded1e327bd1799bfd280112f2823c2f0b1': 'Key cc1dbdded1e327bd1799bfd280112f2823c2f0b1 not found in /da5_fast/All.sha1c/commit_76.tch'}

 37%|███▋      | 842/2274 [14:29<24:40,  1.03s/it]

Got Errors {'cfbadbd37817808a8a6e39aa8e6fd4a7e070c676': 'Key cfbadbd37817808a8a6e39aa8e6fd4a7e070c676 not found in /da5_fast/All.sha1c/commit_79.tch'}

 37%|███▋      | 844/2274 [14:31<24:36,  1.03s/it]

Got Errors {'d15215c7b630b1535f7036c98ead2788c73a37d6': 'Key d15215c7b630b1535f7036c98ead2788c73a37d6 not found in /da5_fast/All.sha1c/commit_81.tch'}

 37%|███▋      | 845/2274 [14:32<24:36,  1.03s/it]

Got Errors {'d1d1353e115dd5a946dfec5ba063270871c99e14': 'Key d1d1353e115dd5a946dfec5ba063270871c99e14 not found in /da5_fast/All.sha1c/commit_81.tch'}

 37%|███▋      | 850/2274 [14:37<24:33,  1.03s/it]

Got Errors {'d5fa1d915ed970356996457af82de06b8c223f00': 'Key d5fa1d915ed970356996457af82de06b8c223f00 not found in /da5_fast/All.sha1c/commit_85.tch'}

 37%|███▋      | 852/2274 [14:39<24:26,  1.03s/it]

Got Errors {'d7afd4132e93a6d1ec0d020b9ee331dae8717a7c': 'Key d7afd4132e93a6d1ec0d020b9ee331dae8717a7c not found in /da5_fast/All.sha1c/commit_87.tch'}

 38%|███▊      | 854/2274 [14:41<24:22,  1.03s/it]

Got Errors {'d923c04f65c70d2a9b1ed7b9d67674e37a14e296': 'Key d923c04f65c70d2a9b1ed7b9d67674e37a14e296 not found in /da5_fast/All.sha1c/commit_89.tch'}

 38%|███▊      | 859/2274 [14:46<24:19,  1.03s/it]

Got Errors {'dcb0a32e57ce254b4e57933c5551e7a3a8eeb657': 'Key dcb0a32e57ce254b4e57933c5551e7a3a8eeb657 not found in /da5_fast/All.sha1c/commit_92.tch'}

 38%|███▊      | 861/2274 [14:48<24:18,  1.03s/it]

Got Errors {'ddbccd0803496c4fb5aef4dbd399b7912fa101b2': 'Key ddbccd0803496c4fb5aef4dbd399b7912fa101b2 not found in /da5_fast/All.sha1c/commit_93.tch', 'dde745c6dfebc669d2061f2c2ce116e8723c4ec4': 'Key dde745c6dfebc669d2061f2c2ce116e8723c4ec4 not found in /da5_fast/All.sha1c/commit_93.tch'}

 38%|███▊      | 862/2274 [14:49<24:17,  1.03s/it]

Got Errors {'de523db18f89a63c67c2fa6635b2eeb79d346c3f': 'Key de523db18f89a63c67c2fa6635b2eeb79d346c3f not found in /da5_fast/All.sha1c/commit_94.tch'}

 38%|███▊      | 863/2274 [14:50<24:14,  1.03s/it]

Got Errors {'df4bb02662a8df72f17ca9a4165c56291bcbbd23': 'Key df4bb02662a8df72f17ca9a4165c56291bcbbd23 not found in /da5_fast/All.sha1c/commit_95.tch'}

 38%|███▊      | 864/2274 [14:51<24:11,  1.03s/it]

Got Errors {'dfa0c8ea3365b45e037a7be39a2820683da70eda': 'Key dfa0c8ea3365b45e037a7be39a2820683da70eda not found in /da5_fast/All.sha1c/commit_95.tch'}

 38%|███▊      | 865/2274 [14:52<24:11,  1.03s/it]

Got Errors {'e02d4ff199016785f0bf7f18b1ca558ef918ca83': 'Key e02d4ff199016785f0bf7f18b1ca558ef918ca83 not found in /da5_fast/All.sha1c/commit_96.tch'}

 38%|███▊      | 866/2274 [14:53<24:11,  1.03s/it]

Got Errors {'e0af1f404bc90f842706db996c7bc17ee5df324d': 'Key e0af1f404bc90f842706db996c7bc17ee5df324d not found in /da5_fast/All.sha1c/commit_96.tch'}

 38%|███▊      | 869/2274 [14:56<24:09,  1.03s/it]

Got Errors {'e3dbc9b1aab46fbf13e974d87d141d546883faa7': 'Key e3dbc9b1aab46fbf13e974d87d141d546883faa7 not found in /da5_fast/All.sha1c/commit_99.tch'}

 38%|███▊      | 871/2274 [14:58<24:06,  1.03s/it]

Got Errors {'e48aa1fc1114f4952f3a022d13f7d766d1ced138': 'Key e48aa1fc1114f4952f3a022d13f7d766d1ced138 not found in /da5_fast/All.sha1c/commit_100.tch'}

 38%|███▊      | 872/2274 [14:59<24:04,  1.03s/it]

Got Errors {'e5050d1fdf41f483a9bd426899d27d4e674428bd': 'Key e5050d1fdf41f483a9bd426899d27d4e674428bd not found in /da5_fast/All.sha1c/commit_101.tch'}

 38%|███▊      | 873/2274 [15:01<24:03,  1.03s/it]

Got Errors {'e5f3909a9457e0d103a8550973fcab253ae854d6': 'Key e5f3909a9457e0d103a8550973fcab253ae854d6 not found in /da5_fast/All.sha1c/commit_101.tch', 'e617db9fcd12de667e8728ee05976cec6c8888ce': 'Key e617db9fcd12de667e8728ee05976cec6c8888ce not found in /da5_fast/All.sha1c/commit_102.tch'}

 38%|███▊      | 875/2274 [15:03<24:00,  1.03s/it]

Got Errors {'e731fc57fae4ec9b1bb396fa88719cb62d88bd7c': 'Key e731fc57fae4ec9b1bb396fa88719cb62d88bd7c not found in /da5_fast/All.sha1c/commit_103.tch'}

 39%|███▊      | 876/2274 [15:04<24:00,  1.03s/it]

Got Errors {'e87d8f6bdca20043ee48e3acdcbfe64cfea9bd45': 'Key e87d8f6bdca20043ee48e3acdcbfe64cfea9bd45 not found in /da5_fast/All.sha1c/commit_104.tch'}

 39%|███▊      | 878/2274 [15:06<23:58,  1.03s/it]

Got Errors {'e96980d4ee9f144eecef1fb05b08914f294b3ddf': 'Key e96980d4ee9f144eecef1fb05b08914f294b3ddf not found in /da5_fast/All.sha1c/commit_105.tch'}

 39%|███▊      | 879/2274 [15:07<23:57,  1.03s/it]

Got Errors {'e9e90ac099819724c9e60675f07fda29c9fc7e3e': 'Key e9e90ac099819724c9e60675f07fda29c9fc7e3e not found in /da5_fast/All.sha1c/commit_105.tch'}

 39%|███▊      | 881/2274 [15:09<23:57,  1.03s/it]

Got Errors {'eb625b8ae631a9f56832bd9089faccaf24572026': 'Key eb625b8ae631a9f56832bd9089faccaf24572026 not found in /da5_fast/All.sha1c/commit_107.tch', 'eb6fa411d169ef481dc329b8a4e0db0be46c0a11': 'Key eb6fa411d169ef481dc329b8a4e0db0be46c0a11 not found in /da5_fast/All.sha1c/commit_107.tch'}

 39%|███▉      | 882/2274 [15:10<23:54,  1.03s/it]

Got Errors {'eba1e75be3b8f8e1979b6fa78e84d55f069dae1a': 'Key eba1e75be3b8f8e1979b6fa78e84d55f069dae1a not found in /da5_fast/All.sha1c/commit_107.tch', 'ec0f39beb8eaecbb4296f4df4ebb686d5d490fdf': 'Key ec0f39beb8eaecbb4296f4df4ebb686d5d490fdf not found in /da5_fast/All.sha1c/commit_108.tch'}

 39%|███▉      | 886/2274 [15:14<23:51,  1.03s/it]

Got Errors {'ef99e2d65987b063e0d5094df4458be35d74576d': 'Key ef99e2d65987b063e0d5094df4458be35d74576d not found in /da5_fast/All.sha1c/commit_111.tch'}

 39%|███▉      | 888/2274 [15:16<23:50,  1.03s/it]

Got Errors {'f19d47bc7e4234e1da789204e8fe4bf5547ea8ed': 'Key f19d47bc7e4234e1da789204e8fe4bf5547ea8ed not found in /da5_fast/All.sha1c/commit_113.tch'}

 40%|███▉      | 899/2274 [15:27<23:38,  1.03s/it]

Got Errors {'f77b7a67f1d3be69333976f9a821643d7c2a3747': 'Key f77b7a67f1d3be69333976f9a821643d7c2a3747 not found in /da5_fast/All.sha1c/commit_119.tch'}

 40%|███▉      | 901/2274 [15:29<23:35,  1.03s/it]

Got Errors {'f84a05fcee319a72216293f12814eaa4fd6eabf9': 'Key f84a05fcee319a72216293f12814eaa4fd6eabf9 not found in /da5_fast/All.sha1c/commit_120.tch', 'f8ac6b6ab601258b423c1df706b72425ec920ace': 'Key f8ac6b6ab601258b423c1df706b72425ec920ace not found in /da5_fast/All.sha1c/commit_120.tch'}

 40%|███▉      | 902/2274 [15:30<23:34,  1.03s/it]

Got Errors {'f955eea01360272cdac004344a54426809d7642f': 'Key f955eea01360272cdac004344a54426809d7642f not found in /da5_fast/All.sha1c/commit_121.tch'}

 40%|███▉      | 908/2274 [15:37<23:33,  1.03s/it]

Got Errors {'fd4fe5a61b8fce59f616073a3110f48eb145cf78': 'Key fd4fe5a61b8fce59f616073a3110f48eb145cf78 not found in /da5_fast/All.sha1c/commit_125.tch'}

 40%|████      | 911/2274 [15:40<23:28,  1.03s/it]

Got Errors {'ff85bc8665736f293cd03d38b0db0bc3c16b9b23': 'Key ff85bc8665736f293cd03d38b0db0bc3c16b9b23 not found in /da5_fast/All.sha1c/commit_127.tch'}

100%|██████████| 2274/2274 [39:03<00:00,  1.03s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,014d06ce8337aab2b4d7e9da90d2d0d22537d118,47538609f59c6da7ae35aec116b1ce81607a436d,[909b3cedd5d3756829cd03fcb2caa925a909a090],Muhammad Saad Shamim <sa501428@gmail.com>,1743867731,-0400,Muhammad Saad Shamim <sa501428@gmail.com>,1743867731,-0400,parallelize getting blocks\n,014d06ce8337aab2b4d7e9da90d2d0d22537d118,aidenlab_straw
1,02ef30c2693b1cba6fd1e5d2d694803aeed0403d,0d917067d4beba5b9beb6fc93c09f6e6c26ed315,"[a69b35326e0568b3114be921d352780c8eab5251, 409...",Muhammad Saad Shamim <sa501428@gmail.com>,1643839632,-0600,GitHub <noreply@github.com>,1643839632,-0600,Merge pull request #91 from sa501428/helper3\n...,02ef30c2693b1cba6fd1e5d2d694803aeed0403d,aidenlab_straw

In [23]:
# what does the first record looks like?
# commit  parents
commit_data = pd.read_csv("df_commit_data.csv")
# print(commit_data[1])
df_commit_data = pd.DataFrame(commit_data)
# v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
# print(v)
# print(commit_data)
df_commit_data.head(10)

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,014d06ce8337aab2b4d7e9da90d2d0d22537d118,47538609f59c6da7ae35aec116b1ce81607a436d,['909b3cedd5d3756829cd03fcb2caa925a909a090'],Muhammad Saad Shamim <sa501428@gmail.com>,1743867731,-400,Muhammad Saad Shamim <sa501428@gmail.com>,1743867731,-400,parallelize getting blocks\n,014d06ce8337aab2b4d7e9da90d2d0d22537d118,aidenlab_straw
1,02ef30c2693b1cba6fd1e5d2d694803aeed0403d,0d917067d4beba5b9beb6fc93c09f6e6c26ed315,"['a69b35326e0568b3114be921d352780c8eab5251', '...",Muhammad Saad Shamim <sa501428@gmail.com>,1643839632,-600,GitHub <noreply@github.com>,1643839632,-600,Merge pull request #91 from sa501428/helper3\n...,02ef30c2693b1cba6fd1e5d2d694803aeed0403d,aidenlab_straw
2,0397a5027626eab94a326650cb7bf8bf73e6084c,456d17648ba913c458553d083cdd48308d5cc0b9,['fefd0476927b064b004e5df0eb83bf1db717b6e7'],nchernia <nchernia@gmail.com>,1476365702,200,nchernia <nchernia@gmail.com>,1476365702,200,updated README\n,0397a5027626eab94a326650cb7bf8bf73e6084c,aidenlab_straw
3,03cf1d6674f4d3eeed208f55bd5e31f74b381151,24dec8256fdc1e23a175b012100725e23290aeb6,['b2cbe5664bc878d6bf67f9cb82db2101bba0423d'],Muhammad S Shamim <sa501428@gmail.com>,1644528519,-600,Muhammad S Shamim <sa501428@gmail.com>,1644528519,-600,new usage\n,03cf1d6674f4d3eeed208f55bd5e31f74b381151,aidenlab_straw
4,03fbfdc1d863e8aed6ce70bee27c54daab2d388b,310b9d52339e5e5e301189c44ed28f360015b6f5,['c92b9167129e6c56e9eb02edc54d6f726b756a62'],Dimos Goundaroulis <dgound@gmail.com>,1632171347,-500,Dimos Goundaroulis <dgound@gmail.com>,1632171347,-500,published v1.0.0.1 to pypi.org\n,03fbfdc1d863e8aed6ce70bee27c54daab2d388b,aidenlab_straw
5,043329007b29d5b1cd79da01ba6f72a27606bd7d,e548ebd32694d6a6ea6174e63d12253fb41f55d7,"['fc1ddf5978b577caec992809b4249a89815465d0', '...",Muhammad Saad Shamim <sa501428@gmail.com>,1743906200,-500,GitHub <noreply@github.com>,1743906200,-500,Merge branch 'master' into temp_merge,043329007b29d5b1cd79da01ba6f72a27606bd7d,aidenlab_straw
6,043684bef67e20f1e3543063be76830e4c299c78,9756c0b3d14ae3e5efc4795fa3901854e86bdcae,"['a015f83114788d7ab97e0338c29c14b92e768d86', '...",Muhammad Saad Shamim <sa501428@gmail.com>,1621030440,-500,Muhammad Saad Shamim <sa501428@gmail.com>,1621030440,-500,Merge branch 'aidenlab:master' into master\n,043684bef67e20f1e3543063be76830e4c299c78,aidenlab_straw
7,0542e0fdbac861f172b286a3ddd98248fb4b830f,bf5c8c890bf06e2d64423f137cc3c25484f783e1,['85045e5092a4858edddf027be1010a084e48921b'],nchernia <nchernia@gmail.com>,1571860390,-400,nchernia <nchernia@gmail.com>,1571860390,-400,updating since norm can be arbitrary\n,0542e0fdbac861f172b286a3ddd98248fb4b830f,aidenlab_straw
8,055d71f3203cd22026296d4e0a99506b356a4c78,d613de3f99c5c12d8d3fc513ec61f45e0f1ca4a5,['61d1d891cc1bcc26ff2bad060db1d68b52de8369'],nchernia <nchernia@gmail.com>,1579892580,-500,nchernia <nchernia@gmail.com>,1579892580,-500,changes to be consistent with pybind version\n,055d71f3203cd22026296d4e0a99506b356a4c78,aidenlab_straw
9,05f413f4207fd01abed54155563eb43d3c582bdb,d004be092e75420fe702ae18ca9bd85f092b5280,['61d1d891cc1bcc26ff2bad060db1d68b52de8369'],nchernia <neva@broadinstitute.org>,1579891694,-500,GitHub <noreply@github.com>,1579891694,-500,Update README.md,05f413f4207fd01abed54155563eb43d3c582bdb,aidenlab_straw

In [9]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

TypeError: string indices must be integers, not 'str'

In [6]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,ohdsi_patientlevelprediction,014d06ce8337aab2b4d7e9da90d2d0d22537d118,Muhammad Saad Shamim <sa501428@gmail.com>,1743867731,parallelize getting blocks\n

In [7]:
#mode a means append, so you have all your projects in the same file
yournetid='econstan'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github

In [13]:
'''
Notes and Tips
what kind of source is worldofcode.org?
pay attention to how many commits you are getting, check for errors
you may need to retrieve commit sha1's first, then get commit content in batches
validation: does the number of commits or authors match that on GH?
WoC data is up to Jan 2025, so there may be some projects with later commits on GH

'''
import requests
# 1. loop through all project github repos

project_names = [
    "aidenlab/straw",
    "corybrunson/ggalluvial",
    "snowleopard/alga",
    "maximecb/gym-minigrid",
    "seung-lab/cloud-volume",
    "STVIR/pysot",
    "google-research/torchsde",
    "tidymodels/rsample",
    "coin-or/Ipopt",
    "OHDSI/PatientLevelPrediction",
]

github_links = [
    "https://github.com/aidenlab/straw",
    "https://github.com/corybrunson/ggalluvial",
    "https://github.com/snowleopard/alga",
    "https://github.com/maximecb/gym-minigrid",
    "https://github.com/seung-lab/cloud-volume",
    "https://github.com/STVIR/pysot",
    "https://github.com/google-research/torchsde",
    "https://github.com/tidymodels/rsample",
    "https://github.com/coin-or/Ipopt",
    "https://github.com/OHDSI/PatientLevelPrediction",
]

# 2. report # of stars, # forks, last commit date - Part 1 step 4 

session = requests.Session()
session.headers.update({"Accept": "application/vnd.github+json"})

project_data = []

for project in tqdm(projects):
    # Get stars, forks, and the current repository name
    response = session.get(
        f"https://api.github.com/repos/{project}",
        timeout=30,
    )
    response.raise_for_status()
    repo = response.json()
    response = session.get(
        f"https://api.github.com/repos/{repo['full_name']}/commits",
        params={"sha": repo["default_branch"], "per_page": 1},
        timeout=30,
    )
    response.raise_for_status()
    commits = response.json()

    project_data.append({
        "project": project,
        "github_url": repo["html_url"],
        "stars": repo["stargazers_count"],
        "forks": repo["forks_count"],
        "last_commit_date": (
            commits[0]["commit"]["committer"]["date"]
            if commits else None
        ),
    })

df_project_data = pd.DataFrame(project_data)

df_project_data.to_csv("df_project_data.csv", index=False)
df_project_data

# 3. report # of commits, # authors, max time, min time - Part 1 step 5

df_summary = (
    df_commit_data.groupby("project")
    .agg(
        number_of_commits=("commit", "nunique"),
        number_of_authors=("author", "nunique"),
        min_time=("committer_time", "min"),
        max_time=("committer_time", "max"),
    )
    .reset_index()
)

# the times aren't readable
for column in ["min_time", "max_time"]:
    df_summary[column] = pd.to_datetime(
        df_summary[column], unit="s", utc=True
    )

df_summary.to_csv("commits_authors_times.txt", sep="\t", index=False)
df_summary

 80%|████████  | 8/10 [00:00<00:00, 12.63it/s]

HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/coin-or/Ipopt/commits?sha=stable%2F3.14&per_page=1

In [33]:

# 4. make CSV of projects information - econstan_project_summary.csv
# Part 1 step 6

# all the commits are saved to the csv called df_commit_data
# commit_data = pd.read_csv("df_commit_data.csv")
# print(commit_data[1])
# df_commit_data = pd.DataFrame(commit_data)
# v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
# print(v)
# print(commit_data)
df_commit_data.head(10)

new_row = []

# for project_name in df_commit_data['project'].unique():
# 	print(project_name)
for index, entry in df_commit_data.iterrows():
	# print(entry)
	new_row.append({
		"project_wocid": entry["project"],
		"commit_sha1": entry["sha1"],
		"author": entry["author"],
		"time": entry["committer_time"],
		"commit message": entry["message"]
	})

df_step_6 = pd.DataFrame(new_row)

df_step_6.to_csv("econstan_project_summary.csv", index=False)
df_step_6

,project_wocid,commit_sha1,author,time,commit message
0,aidenlab_straw,014d06ce8337aab2b4d7e9da90d2d0d22537d118,Muhammad Saad Shamim <sa501428@gmail.com>,1743867731,parallelize getting blocks\n
1,aidenlab_straw,02ef30c2693b1cba6fd1e5d2d694803aeed0403d,Muhammad Saad Shamim <sa501428@gmail.com>,1643839632,Merge pull request #91 from sa501428/helper3\n...
2,aidenlab_straw,0397a5027626eab94a326650cb7bf8bf73e6084c,nchernia <nchernia@gmail.com>,1476365702,updated README\n
3,aidenlab_straw,03cf1d6674f4d3eeed208f55bd5e31f74b381151,Muhammad S Shamim <sa501428@gmail.com>,1644528519,new usage\n
4,aidenlab_straw,03fbfdc1d863e8aed6ce70bee27c54daab2d388b,Dimos Goundaroulis <dgound@gmail.com>,1632171347,published v1.0.0.1 to pypi.org\n
...,...,...,...,...,...
22527,ohdsi_patientlevelprediction,ff93a358f46c27533d856442c575b7359d265364,egillax <egillax@gmail.com>,1682509725,remove docs folder\n
22528,ohdsi_patientlevelprediction,ffaec05960131a6324ac54662abad0dd3795038e,aniekmarkus <a.markus@erasmusmc.nl>,1677593502,Merge branch 'main' of https://github.com/mi-e...
22529,ohdsi_patientlevelprediction,ffc66ec7d1a2f7b93ea42bf66141161924aa8009,Jenna Reps <jreps@its.jnj.com>,1654113258,Update settings.R\n\n- updated shiny model set...
22530,ohdsi_patientlevelprediction,ffcdc0a064e22d24360dd9e54d25e17649de55eb,egillax <egillax@gmail.com>,1715761040,Deploying to gh-pages from @ OHDSI/PatientLeve...
22531,ohdsi_patientlevelprediction,ffddde64d63e8d0ca4eced5a2ec2226a75880da7,egillax <egillax@gmail.com>,1744633969,"Revert ""Merge pull request #563 from OHDSI/541..."

In [48]:
# PART 2 ============================================================================


# Step 1 and 2
# month, # of commits
# Convert Unix timestamps to UTC dates
dates = pd.to_datetime(df_step_6["time"], unit="s", utc=True)
df_step_6["Month"] = dates.dt.strftime("%Y-%m")

monthly_commits = (
    df_step_6.groupby(["project_wocid", "Month"])["commit_sha1"]
    .nunique()
    .reset_index(name="#Commits")
)

# ADD optional section to fill in 0's where there are no commits for that month

filled_projects = []

for project_id, project_data in monthly_commits.groupby("project_wocid"):
    project_data = project_data.set_index("Month")

    # Include every month from this project's first to last month
    all_months = pd.period_range(
        start=project_data.index.min(),
        end=project_data.index.max(),
        freq="M",
    ).astype(str)

    project_data = project_data.reindex(all_months, fill_value='0')
    project_data.index.name = "Month"
    project_data["project_wocid"] = project_id

    filled_projects.append(project_data.reset_index())

monthly_commits = pd.concat(filled_projects, ignore_index=True)
monthly_commits = monthly_commits[
    ["project_wocid", "Month", "#Commits"]
]

# END optional section
monthly_commits["#Commits"] = monthly_commits["#Commits"].astype(int)
monthly_commits.to_csv("econstan_commits_timeseries.csv", index=False)
monthly_commits




# Step 3 and 4
# create line plot of the monthly data
# Plot Format:
# X-axis = months (YYYY-MM)
# Y-axis = number of commits
# Title = WOCProjectID
# Add axis labels and grid lines
# Save the plot as: netid_timeseries_<WOCProjectID>.png
# Export resolution: ≥300 DPI

import matplotlib.pyplot as plt

# Load CSV
# monthly = pd.read_csv("econstan_commits_timeseries.csv", sep=";")
for project_id, project_data in monthly_commits.groupby("project_wocid"):
	project_data = project_data.sort_values("Month")
      
	plt.figure(figsize=(10, 5))
	plt.plot(
		project_data["Month"],
		project_data["#Commits"],
		marker="o",
		linestyle="-",
	)

	plt.xlabel("Time (YYYY-MM)")
	plt.ylabel("Number of Commits")
	plt.title(f"Commit Activity: {project_id}")
	plt.grid(True)
	plt.xticks(rotation=45)
	plt.tight_layout()

	graph_filename = f"econstan_timeseries_{project_id}.png"
	plt.savefig(graph_filename, dpi=300)
	plt.close()

In [49]:
#  part 2 second section -- find the longest inactivity gap
project_mapping = {
    "aidenlab_straw": "aidenlab/straw",
    "corybrunson_ggalluvial": "corybrunson/ggalluvial",
    "snowleopard_alga": "snowleopard/alga",
    "maximecb_gym-minigrid": "maximecb/gym-minigrid",
    "seung-lab_cloud-volume": "seung-lab/cloud-volume",
    "stvir_pysot": "STVIR/pysot",
    "google-research_torchsde": "google-research/torchsde",
    "tidymodels_rsample": "tidymodels/rsample",
    "coin-or_ipopt": "coin-or/Ipopt",
    "ohdsi_patientlevelprediction": "OHDSI/PatientLevelPrediction",
}

columns = [
    "project",
    "number_of_commits",
    "number_of_authors",
    "max_time",
    "min_time",
    "number_of_stars",
    "number_of_forks",
    "last_commit_date",
    "LongestGapStart",
    "LongestGapEnd",
    "LongestGapLength",
	]

df_project_stats = pd.DataFrame(columns=columns)
github_stats = pd.read_csv("df_project_data.csv").set_index("project")

new_rows = []

# for each project, find the longest gap with no commits
for project_id, project_data in monthly_commits.groupby("project_wocid"):

    # get all data just for one project
    project_data = project_data.sort_values("Month")

    # track the max length of a gap
    longest_start = None
    longest_end = None
    longest_length = 0

    current_start = None
    current_length = 0


    # find the first month with no commits
    # count consecutive months with no commits
    for index, entry in project_data.iterrows():
        if entry["#Commits"] == 0:
            if current_length == 0:
                current_start = entry["Month"]

            current_length += 1

            if current_length > longest_length:
                longest_start = current_start
                longest_end = entry["Month"]
                longest_length = current_length
        else:
            current_start = None
            current_length = 0

    # Get commit records for this project
    commits = df_step_6[
        df_step_6["project_wocid"] == project_id
    ]

    times = pd.to_numeric(commits["time"], errors="raise")
    github_project = project_mapping[project_id]
    gh = github_stats.loc[github_project]

    # Values match the order of columns above
    new_rows.append([
        project_id,
        commits["commit_sha1"].nunique(),
        commits["author"].nunique(),
        pd.to_datetime(times.max(), unit="s", utc=True),
        pd.to_datetime(times.min(), unit="s", utc=True),
        gh["stars"],
        gh["forks"],
        gh["last_commit_date"],
        longest_start,
        longest_end,
        longest_length,
    ])


df_project_stats = pd.DataFrame(new_rows, columns=columns)
df_project_stats.to_csv("econstan_project_stats.csv", index=False)
df_project_stats

,project,number_of_commits,number_of_authors,max_time,min_time,number_of_stars,number_of_forks,last_commit_date,LongestGapStart,LongestGapEnd,LongestGapLength
0,aidenlab_straw,453,36,2025-06-29 21:21:26+00:00,2016-07-28 19:09:03+00:00,70,35,2025-04-06T02:23:28Z,2024-04,2025-03,12
1,coin-or_ipopt,8374,74,2026-03-09 19:56:22+00:00,2004-10-21 01:03:09+00:00,1790,318,2026-08-27T14:02:53Z,2017-07,2017-10,4
2,corybrunson_ggalluvial,864,14,2026-04-11 23:12:25+00:00,2016-05-16 21:24:54+00:00,524,34,2026-02-22T13:12:42Z,2023-08,2024-05,10
3,google-research_torchsde,615,23,2025-01-14 13:55:14+00:00,2020-07-06 23:58:04+00:00,1727,231,2024-12-30T10:52:51Z,2021-08,2023-06,23
4,maximecb_gym-minigrid,2115,193,2025-10-27 06:30:54+00:00,2017-12-13 17:26:52+00:00,2518,654,2026-09-10T21:43:25Z,2025-03,2025-05,3
5,ohdsi_patientlevelprediction,2679,63,2025-10-29 13:40:38+00:00,2015-03-22 19:08:53+00:00,222,96,2026-09-21T11:43:21Z,2019-09,2019-09,1
6,seung-lab_cloud-volume,3487,51,2025-10-31 19:38:23+00:00,2017-07-25 17:34:30+00:00,175,54,2026-09-28T22:12:01Z,2021-09,2021-09,1
7,snowleopard_alga,1997,66,2025-08-19 08:34:20+00:00,2016-12-05 00:30:03+00:00,763,74,2025-07-13T10:07:51Z,2023-05,2023-10,6
8,stvir_pysot,95,24,2025-06-22 13:38:05+00:00,2019-05-07 15:32:11+00:00,4603,1110,2025-06-22T03:59:22Z,2021-04,2023-03,24
9,tidymodels_rsample,1853,80,2026-04-14 13:53:36+00:00,2017-04-22 19:19:58+00:00,343,68,2026-09-17T17:57:29Z,2024-10,2025-02,5

In [54]:
# ADD NumCommitsAfterLastGap, NumberOfGapsInTimeline, ActivityPattern

import pandas as pd

stats = pd.read_csv("econstan_project_stats.csv")
stats["ActivityPattern"] = pd.Series(
    pd.NA, index=stats.index, dtype="string"
)

monthly = monthly_commits.copy()
monthly["#Commits"] = monthly["#Commits"].astype(int)
monthly["Month"] = pd.to_datetime(monthly["Month"], format="%Y-%m")

# add the activity pattern assessment
# steady, rising, declining, U-shaped, cyclical, irregular
activity_patterns = {
    "aidenlab_straw": "irregular",
    "corybrunson_ggalluvial": "declining",
    "snowleopard_alga": "declining",
    "maximecb_gym-minigrid": "U-shaped",
    "seung-lab_cloud-volume": "U-shaped",
    "stvir_pysot": "declining",
    "google-research_torchsde": "declining",
    "tidymodels_rsample": "inclining",
    "coin-or_ipopt": "steady",
    "ohdsi_patientlevelprediction": "inclining",
}

for index, row in stats.iterrows():
    project_id = row["project"]

    timeline = monthly[
        monthly["project_wocid"] == project_id
    ].sort_values("Month")

    # Count commits strictly after the longest gap's final month
    gap_end = row["LongestGapEnd"]

    if pd.notna(gap_end):
        gap_end = pd.to_datetime(gap_end, format="%Y-%m")
        commits_after = timeline.loc[
            timeline["Month"] > gap_end, "#Commits"
        ].sum()
    else:
        # No inactivity gap: use the entire timeline
        commits_after = timeline["#Commits"].sum()

    # Count separate runs of at least three inactive months
    number_of_gaps = 0
    inactive_months = 0

    for count in timeline["#Commits"]:
        if count == 0:
            inactive_months += 1

            # Count the run once, when it reaches three months
            if inactive_months == 3:
                number_of_gaps += 1
        else:
            inactive_months = 0

    stats.loc[index, "NumCommitsAfterLastGap"] = commits_after
    stats.loc[index, "NumberOfGapsInTimeline"] = number_of_gaps
    stats.loc[index, "ActivityPattern"] = str(activity_patterns[project_id])

stats[["NumCommitsAfterLastGap", "NumberOfGapsInTimeline"]] = (
    stats[["NumCommitsAfterLastGap", "NumberOfGapsInTimeline"]]
    .astype(int)
)

stats.to_csv("econstan_project_stats.csv", index=False)
stats

,project,number_of_commits,number_of_authors,max_time,min_time,number_of_stars,number_of_forks,last_commit_date,LongestGapStart,LongestGapEnd,LongestGapLength,NumCommitsAfterLastGap,NumberOfGapsInTimeline,ActivityPattern
0,aidenlab_straw,453,36,2025-06-29 21:21:26+00:00,2016-07-28 19:09:03+00:00,70,35,2025-04-06T02:23:28Z,2024-04,2025-03,12,27,5,irregular
1,coin-or_ipopt,8374,74,2026-03-09 19:56:22+00:00,2004-10-21 01:03:09+00:00,1790,318,2026-08-27T14:02:53Z,2017-07,2017-10,4,1310,2,steady
2,corybrunson_ggalluvial,864,14,2026-04-11 23:12:25+00:00,2016-05-16 21:24:54+00:00,524,34,2026-02-22T13:12:42Z,2023-08,2024-05,10,24,7,declining
3,google-research_torchsde,615,23,2025-01-14 13:55:14+00:00,2020-07-06 23:58:04+00:00,1727,231,2024-12-30T10:52:51Z,2021-08,2023-06,23,34,3,declining
4,maximecb_gym-minigrid,2115,193,2025-10-27 06:30:54+00:00,2017-12-13 17:26:52+00:00,2518,654,2026-09-10T21:43:25Z,2025-03,2025-05,3,19,1,U-shaped
5,ohdsi_patientlevelprediction,2679,63,2025-10-29 13:40:38+00:00,2015-03-22 19:08:53+00:00,222,96,2026-09-21T11:43:21Z,2019-09,2019-09,1,1856,0,inclining
6,seung-lab_cloud-volume,3487,51,2025-10-31 19:38:23+00:00,2017-07-25 17:34:30+00:00,175,54,2026-09-28T22:12:01Z,2021-09,2021-09,1,1009,0,U-shaped
7,snowleopard_alga,1997,66,2025-08-19 08:34:20+00:00,2016-12-05 00:30:03+00:00,763,74,2025-07-13T10:07:51Z,2023-05,2023-10,6,53,5,declining
8,stvir_pysot,95,24,2025-06-22 13:38:05+00:00,2019-05-07 15:32:11+00:00,4603,1110,2025-06-22T03:59:22Z,2021-04,2023-03,24,14,5,declining
9,tidymodels_rsample,1853,80,2026-04-14 13:53:36+00:00,2017-04-22 19:19:58+00:00,343,68,2026-09-17T17:57:29Z,2024-10,2025-02,5,156,1,inclining

## Interpretation

- add an explanation for the trends you noted. See the definitions below. Also specify the number of gaps (of at least three months of inactivity) are there for each project.
- example Trends:

- - steady, rising, declining, U-shaped: Long-term, general movements in activity levels. An upward trend might indicate that a person is becoming more active over several months, while a downward trend could signal a decrease in mobility.

- - Seasonal/Cyclical patterns: Predictable and repeated patterns of activity that occur at fixed intervals, such as quarterly or annually.

- - Irregular or random variations: Unpredictable changes in activity that cannot be explained by trends or seasonal patterns.